// import styles from '../styles/Home.module.css'
import React from 'react'
import { Route } from 'react-router'
import Navbar from './components/navbar'
import TextEditor from './components/text-editor'

const Home = () => {
  return (
    <div className={ {/*styles.container*/} }>
      {/* <Head>
        <title>Stift</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <div className='flex flex-col items-center'>
        <Navbar />
        <main className='w-3/5 px-2 py-3'>
          <div className='flex flex-col items-center px-4'>
            <span className='text-lg pb-4'>
              Archive
            </span>

            <table className="mt-8 text-sm text-left w-full xl:w-3/4">
              <tbody>
                <tr className="bg-white border-b">
                  <th scope="row" className="font-normal py-4  whitespace-nowrap">
                    <Route path='/record/id' component={TextEditor}>
                      my first record
                    </Route>
                  </th>
                  <td className="px-6 py-4 font-light">
                    <Route href='/record/id'>
                      date
                    </Route>
                  </td>
                </tr>
                <tr className="bg-white border-b">
                  <th scope="row" className="py-4  font-normal whitespace-nowrap">
                    <Route href='/record/id'>
                      my second record
                    </Route>
                  </th>
                  <td className="px-6 py-4 font-light">
                    <Route href='/record/id'>
                      date
                    </Route>
                  </td>
                </tr>
                <tr className="bg-white">
                  <th colSpan={2} scope="row" className="text-center py-4 text-gray-400 font-light whitespace-nowrap">
                    <Route href='/record'>
                      New
                    </Route>
                  </th>
                </tr>
              </tbody>
            </table>
          </div>
        </main>
      </div>
    </div>
  )
}

export default Home
