import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import TextEditor from '../components/text-editor'

const Record = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Stift</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='h-screen flex flex-col items-center'>
        <Navbar />

        <div className='w-3/4 xl:w-1/2 mx-2 my-3 '>
          <TextEditor />
        </div>
      </div>

    </div>
  )
}

export default Record
